import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Check, Shield, Truck, QrCode, Link2, AlertTriangle, ArrowRight, Star } from "lucide-react";
import { PLAN_TIERS } from "@/lib/stripe/plans";

export default function LandingPage() {
  const tiers = ["starter", "professional", "business"] as const;
  return (
    <div>
      <section className="py-20 md:py-32 bg-gradient-to-b from-background to-muted/30"><div className="container mx-auto px-4 text-center">
        <Badge variant="secondary" className="mb-4">Cargo theft costs over $223M annually</Badge>
        <h1 className="text-4xl md:text-6xl font-bold tracking-tight mb-6 max-w-3xl mx-auto">Know who is picking up your freight.</h1>
        <p className="text-xl text-muted-foreground mb-8 max-w-2xl mx-auto">FreightVerify provides real-time carrier identity verification and tamper-proof chain of custody to stop cargo theft.</p>
        <div className="flex items-center justify-center gap-4"><Link href="/signup"><Button size="lg" className="gap-2">Start Your 14-Day Free Trial <ArrowRight className="h-4 w-4" /></Button></Link><Link href="/pricing"><Button size="lg" variant="outline">View Pricing</Button></Link></div>
      </div></section>
      <section className="py-20 bg-muted/30"><div className="container mx-auto px-4"><div className="text-center mb-12"><h2 className="text-3xl font-bold mb-4">The Verification Gap</h2><p className="text-muted-foreground max-w-2xl mx-auto">Cargo theft is rising. Double-brokering and identity fraud exploit the gap between tendering a load and verifying pickup.</p></div><div className="grid gap-6 md:grid-cols-3 max-w-4xl mx-auto"><Card><CardContent className="pt-6 text-center"><p className="text-3xl font-bold text-destructive">$223M+</p><p className="text-sm text-muted-foreground mt-1">Annual cargo theft losses</p></CardContent></Card><Card><CardContent className="pt-6 text-center"><p className="text-3xl font-bold text-destructive">+27%</p><p className="text-sm text-muted-foreground mt-1">YoY increase</p></CardContent></Card><Card><CardContent className="pt-6 text-center"><p className="text-3xl font-bold text-destructive">85%</p><p className="text-sm text-muted-foreground mt-1">Involve identity fraud</p></CardContent></Card></div></div></section>
      <section className="py-20"><div className="container mx-auto px-4"><div className="text-center mb-12"><h2 className="text-3xl font-bold mb-4">How FreightVerify Works</h2></div><div className="grid gap-8 md:grid-cols-3 max-w-5xl mx-auto"><div className="text-center"><div className="mx-auto rounded-full bg-primary/10 p-4 w-16 h-16 flex items-center justify-center mb-4"><Truck className="h-8 w-8 text-primary" /></div><h3 className="font-semibold text-lg mb-2">1. Verify Carrier</h3><p className="text-sm text-muted-foreground">FMCSA lookup validates operating authority and safety rating.</p></div><div className="text-center"><div className="mx-auto rounded-full bg-primary/10 p-4 w-16 h-16 flex items-center justify-center mb-4"><QrCode className="h-8 w-8 text-primary" /></div><h3 className="font-semibold text-lg mb-2">2. Assign Load</h3><p className="text-sm text-muted-foreground">Tender loads with secure one-time pickup codes.</p></div><div className="text-center"><div className="mx-auto rounded-full bg-primary/10 p-4 w-16 h-16 flex items-center justify-center mb-4"><Shield className="h-8 w-8 text-primary" /></div><h3 className="font-semibold text-lg mb-2">3. Confirm Pickup</h3><p className="text-sm text-muted-foreground">Driver enters OTP with GPS and photos. Hash-chained for integrity.</p></div></div></div></section>
      <section className="py-20 bg-muted/30"><div className="container mx-auto px-4"><div className="text-center mb-12"><h2 className="text-3xl font-bold mb-4">Key Features</h2></div><div className="grid gap-6 md:grid-cols-2 lg:grid-cols-4 max-w-6xl mx-auto"><Card><CardHeader><div className="rounded-full bg-primary/10 p-2 w-10 h-10 flex items-center justify-center mb-2"><Truck className="h-5 w-5 text-primary" /></div><CardTitle className="text-base">FMCSA Verification</CardTitle></CardHeader><CardContent><p className="text-sm text-muted-foreground">Real-time DOT lookup with authority and safety data.</p></CardContent></Card><Card><CardHeader><div className="rounded-full bg-primary/10 p-2 w-10 h-10 flex items-center justify-center mb-2"><QrCode className="h-5 w-5 text-primary" /></div><CardTitle className="text-base">OTP Pickup Codes</CardTitle></CardHeader><CardContent><p className="text-sm text-muted-foreground">One-time codes for verified driver identity.</p></CardContent></Card><Card><CardHeader><div className="rounded-full bg-primary/10 p-2 w-10 h-10 flex items-center justify-center mb-2"><Link2 className="h-5 w-5 text-primary" /></div><CardTitle className="text-base">Chain of Custody</CardTitle></CardHeader><CardContent><p className="text-sm text-muted-foreground">Immutable, auditable event records.</p></CardContent></Card><Card><CardHeader><div className="rounded-full bg-primary/10 p-2 w-10 h-10 flex items-center justify-center mb-2"><AlertTriangle className="h-5 w-5 text-primary" /></div><CardTitle className="text-base">Anomaly Alerts</CardTitle></CardHeader><CardContent><p className="text-sm text-muted-foreground">Six rules detect fraud patterns automatically.</p></CardContent></Card></div></div></section>
      <section className="py-20" id="pricing"><div className="container mx-auto px-4"><div className="text-center mb-12"><h2 className="text-3xl font-bold mb-4">Simple, Transparent Pricing</h2><p className="text-muted-foreground">14-day free trial. No credit card required.</p></div><div className="grid gap-6 md:grid-cols-3 max-w-5xl mx-auto">{tiers.map((tier) => { const plan = PLAN_TIERS[tier]; const isPopular = tier === "professional"; return (<Card key={tier} className={isPopular ? "border-primary shadow-lg relative" : "relative"}>{isPopular && (<div className="absolute -top-3 left-1/2 -translate-x-1/2"><Badge className="bg-primary text-primary-foreground">Most Popular</Badge></div>)}<CardHeader className="text-center pb-2"><CardTitle className="text-lg">{plan.name}</CardTitle><div className="mt-2"><span className="text-3xl font-bold">{plan.priceDisplay}</span><span className="text-muted-foreground">/mo</span></div></CardHeader><CardContent className="space-y-4"><ul className="space-y-2">{plan.features.map((f) => (<li key={f} className="flex items-start gap-2 text-sm"><Check className="h-4 w-4 text-green-600 mt-0.5 shrink-0" /><span>{f}</span></li>))}</ul><Link href="/signup" className="block"><Button className="w-full" variant={isPopular ? "default" : "outline"}>Start Free Trial</Button></Link></CardContent></Card>); })}</div></div></section>
      <section className="py-20 bg-muted/30"><div className="container mx-auto px-4 text-center"><h2 className="text-3xl font-bold mb-8">Trusted by Freight Brokers</h2><div className="grid gap-6 md:grid-cols-3 max-w-4xl mx-auto">{[{ name: "Sarah M.", role: "VP Operations", quote: "FreightVerify eliminated cargo theft incidents." },{ name: "James R.", role: "Freight Broker", quote: "OTP verification gives shippers confidence." },{ name: "Michelle T.", role: "Logistics Mgr", quote: "Hash-chained logs are invaluable for compliance." }].map((t) => (<Card key={t.name}><CardContent className="pt-6"><div className="flex items-center gap-1 mb-3">{[1,2,3,4,5].map((s) => (<Star key={s} className="h-4 w-4 fill-yellow-400 text-yellow-400" />))}</div><p className="text-sm text-muted-foreground mb-4">{t.quote}</p><div><p className="text-sm font-medium">{t.name}</p><p className="text-xs text-muted-foreground">{t.role}</p></div></CardContent></Card>))}</div></div></section>
      <section className="py-20"><div className="container mx-auto px-4 text-center"><h2 className="text-3xl font-bold mb-4">Ready to secure your freight?</h2><p className="text-muted-foreground mb-8 max-w-xl mx-auto">Join freight brokers who trust FreightVerify for verified carrier identity and tamper-proof chain of custody.</p><Link href="/signup"><Button size="lg" className="gap-2">Start Your 14-Day Free Trial <ArrowRight className="h-4 w-4" /></Button></Link></div></section>
    </div>
  );
}
